// Generated by gencpp from file wzm_1/multiResponse.msg
// DO NOT EDIT!


#ifndef WZM_1_MESSAGE_MULTIRESPONSE_H
#define WZM_1_MESSAGE_MULTIRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wzm_1
{
template <class ContainerAllocator>
struct multiResponse_
{
  typedef multiResponse_<ContainerAllocator> Type;

  multiResponse_()
    : m(0)  {
    }
  multiResponse_(const ContainerAllocator& _alloc)
    : m(0)  {
  (void)_alloc;
    }



   typedef int64_t _m_type;
  _m_type m;





  typedef boost::shared_ptr< ::wzm_1::multiResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wzm_1::multiResponse_<ContainerAllocator> const> ConstPtr;

}; // struct multiResponse_

typedef ::wzm_1::multiResponse_<std::allocator<void> > multiResponse;

typedef boost::shared_ptr< ::wzm_1::multiResponse > multiResponsePtr;
typedef boost::shared_ptr< ::wzm_1::multiResponse const> multiResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wzm_1::multiResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wzm_1::multiResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace wzm_1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::wzm_1::multiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wzm_1::multiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wzm_1::multiResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wzm_1::multiResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wzm_1::multiResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wzm_1::multiResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wzm_1::multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ac4ba103c999804b94081b0534fca93";
  }

  static const char* value(const ::wzm_1::multiResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ac4ba103c999804ULL;
  static const uint64_t static_value2 = 0xb94081b0534fca93ULL;
};

template<class ContainerAllocator>
struct DataType< ::wzm_1::multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wzm_1/multiResponse";
  }

  static const char* value(const ::wzm_1::multiResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wzm_1::multiResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 m\n\
\n\
";
  }

  static const char* value(const ::wzm_1::multiResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wzm_1::multiResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.m);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wzm_1::multiResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wzm_1::multiResponse_<ContainerAllocator>& v)
  {
    s << indent << "m: ";
    Printer<int64_t>::stream(s, indent + "  ", v.m);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WZM_1_MESSAGE_MULTIRESPONSE_H
